<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE ISBNRangeMessage [
<!ELEMENT ISBNRangeMessage (MessageSource?, MessageSerialNumber?, MessageDate, EAN.UCCPrefixes, RegistrationGroups) >
<!ELEMENT MessageSource (#PCDATA) >
<!ELEMENT MessageSerialNumber (#PCDATA) >
<!ELEMENT MessageDate (#PCDATA) >
<!ELEMENT EAN.UCCPrefixes (EAN.UCC+) >
<!ELEMENT RegistrationGroups (Group+) >
<!ELEMENT EAN.UCC (Prefix, Agency, Rules) >
<!ELEMENT Group (Prefix, Agency, Rules) >
<!ELEMENT Rules (Rule+) >
<!ELEMENT Rule (Range, Length) >
<!ELEMENT Prefix (#PCDATA) >
<!ELEMENT Agency (#PCDATA) >
<!ELEMENT Range (#PCDATA) >
<!ELEMENT Length (#PCDATA) >
]>
<ISBNRangeMessage>
  <MessageSource>International ISBN Agency</MessageSource>
  <MessageSerialNumber>05b795ba-5172-4181-b921-69f9f6d0d3d2</MessageSerialNumber>
  <MessageDate>Sat, 2 May 2026 05:43:12 BST</MessageDate>
  <EAN.UCCPrefixes>
    <EAN.UCC>
      <Prefix>978</Prefix>
      <Agency>International ISBN Agency</Agency>
      <Rules>
        <Rule>
          <Range>0000000-5999999</Range>
          <Length>1</Length>
        </Rule>
        <Rule>
          <Range>6000000-6499999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>6500000-6599999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>6600000-6699999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>6700000-6998999</Range>
          <Length>0</Length>
        </Rule>
        <Rule>
          <Range>6999000-6999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>7000000-7999999</Range>
          <Length>1</Length>
        </Rule>
        <Rule>
          <Range>8000000-9499999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>9500000-9899999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>9900000-9989999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9990000-9999999</Range>
          <Length>5</Length>
        </Rule>
      </Rules>
    </EAN.UCC>
    <EAN.UCC>
      <Prefix>979</Prefix>
      <Agency>International ISBN Agency</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0999999</Range>
          <Length>0</Length>
        </Rule>
        <Rule>
          <Range>1000000-1599999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>1600000-7999999</Range>
          <Length>0</Length>
        </Rule>
        <Rule>
          <Range>8000000-8999999</Range>
          <Length>1</Length>
        </Rule>
        <Rule>
          <Range>9000000-9999999</Range>
          <Length>0</Length>
        </Rule>
      </Rules>
    </EAN.UCC>
  </EAN.UCCPrefixes>
  <RegistrationGroups>
    <Group>
      <Prefix>978-0</Prefix>
      <Agency>English language</Agency>
      <Rules>
        <Rule>
          <Range>0000000-1999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2000000-2279999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>2280000-2289999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>2290000-3689999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>3690000-3699999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>3700000-6389999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>6390000-6397999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>6398000-6399999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>6400000-6449999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>6450000-6459999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>6460000-6479999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>6480000-6489999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>6490000-6549999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>6550000-6559999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>6560000-6999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>7000000-8499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8500000-8999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9000000-9003709</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9003710-9003719</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>9003720-9499999</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9500000-9999999</Range>
          <Length>7</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-1</Prefix>
      <Agency>English language</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0099999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>0100000-0299999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>0300000-0349999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>0350000-0399999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>0400000-0479999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>0480000-0499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>0500000-0599999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>0600000-0665999</Range>
          <Length>0</Length>
        </Rule>
        <Rule>
          <Range>0666000-0669999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>0670000-0699999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>0700000-0999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>1000000-3979999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>3980000-5499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>5500000-6499999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>6500000-6799999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>6800000-6859999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>6860000-7139999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>7140000-7169999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>7170000-7319999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>7320000-7399999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>7400000-7619999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>7620000-7634999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>7635000-7649999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>7650000-7749999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>7750000-7753999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>7754000-7763999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>7764000-7764999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>7765000-7769999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>7770000-7782999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>7783000-7899999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>7900000-7999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8000000-8004999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>8005000-8049999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>8050000-8379999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>8380000-8384999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>8385000-8671999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>8672000-8675999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8676000-8697999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>8698000-9159999</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9160000-9165059</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>9165060-9168699</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9168700-9169079</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>9169080-9191639</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9191640-9195649</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>9195650-9195999</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9196000-9196549</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>9196550-9729999</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9730000-9877999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9878000-9911499</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9911500-9911999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>9912000-9989899</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9989900-9999999</Range>
          <Length>7</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-2</Prefix>
      <Agency>French language</Agency>
      <Rules>
        <Rule>
          <Range>0000000-1999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2000000-3499999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>3500000-3999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>4000000-4869999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>4870000-4949999</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>4950000-4959999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>4960000-4966999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>4967000-4969999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>4970000-5279999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>5280000-5299999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>5300000-6999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>7000000-8399999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8400000-8999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9000000-9197999</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9198000-9198099</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9198100-9199429</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9199430-9199689</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>9199690-9499999</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9500000-9999999</Range>
          <Length>7</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-3</Prefix>
      <Agency>German language</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0299999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>0300000-0339999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>0340000-0369999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>0370000-0399999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>0400000-1999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2000000-3129999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>3130000-3139999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>3140000-3899999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>3900000-3999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>4000000-6889999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>6890000-6949999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>6950000-8499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8500000-8999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9000000-9499999</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9500000-9539999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>9540000-9699999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9700000-9849999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>9850000-9995999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9996000-9999999</Range>
          <Length>4</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-4</Prefix>
      <Agency>Japan</Agency>
      <Rules>
        <Rule>
          <Range>0000000-1999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2000000-6999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>7000000-8499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8500000-8999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9000000-9499999</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9500000-9999999</Range>
          <Length>7</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-5</Prefix>
      <Agency>former U.S.S.R</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0049999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>0050000-0099999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>0100000-1999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2000000-3619999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>3620000-3623999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>3624000-3629999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>3630000-4209999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>4210000-4299999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>4300000-4309999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>4310000-4399999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>4400000-4409999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>4410000-4499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>4500000-6039999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>6040000-6049999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>6050000-6999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>7000000-8499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8500000-8999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9000000-9099999</Range>
          <Length>6</Length>
        </Rule>
        <Rule>
          <Range>9100000-9199999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9200000-9299999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9300000-9499999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9500000-9500999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>9501000-9799999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9800000-9899999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9900000-9909999</Range>
          <Length>7</Length>
        </Rule>
        <Rule>
          <Range>9910000-9999999</Range>
          <Length>4</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-600</Prefix>
      <Agency>Iran</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>1000000-4999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>5000000-8999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9000000-9867999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9868000-9929999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9930000-9959999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>9960000-9999999</Range>
          <Length>5</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-601</Prefix>
      <Agency>Kazakhstan</Agency>
      <Rules>
        <Rule>
          <Range>0000000-1999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2000000-6999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>7000000-7999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8000000-8499999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>8500000-9999999</Range>
          <Length>2</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-602</Prefix>
      <Agency>Indonesia</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0699999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>0700000-1399999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>1400000-1499999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>1500000-1699999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>1700000-1999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>2000000-4999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>5000000-5399999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>5400000-5999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>6000000-6199999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>6200000-6999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>7000000-7499999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>7500000-9499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9500000-9999999</Range>
          <Length>5</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-603</Prefix>
      <Agency>Saudi Arabia</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0499999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>0500000-4999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>5000000-7999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>8000000-8999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9000000-9999999</Range>
          <Length>5</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-604</Prefix>
      <Agency>Vietnam</Agency>
      <Rules>
        <Rule>
          <Range>0000000-2999999</Range>
          <Length>1</Length>
        </Rule>
        <Rule>
          <Range>3000000-3999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>4000000-4699999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>4700000-4979999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>4980000-4999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>5000000-8999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>9000000-9799999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>9800000-9999999</Range>
          <Length>4</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-605</Prefix>
      <Agency>Türkiye</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0299999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>0300000-0399999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>0400000-0599999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>0600000-0699999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>0700000-0999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>1000000-1999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>2000000-2399999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>2400000-3999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>4000000-5999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>6000000-7499999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>7500000-7999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8000000-8999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9000000-9999999</Range>
          <Length>4</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-606</Prefix>
      <Agency>Romania</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>1000000-4999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>5000000-7999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>8000000-9099999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9100000-9199999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>9200000-9599999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9600000-9749999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9750000-9999999</Range>
          <Length>3</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-607</Prefix>
      <Agency>Mexico</Agency>
      <Rules>
        <Rule>
          <Range>0000000-2599999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2600000-2649999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>2650000-2699999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>2700000-3999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>4000000-5889999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>5890000-5929999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>5930000-5999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>6000000-6919999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>6920000-6999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>7000000-7499999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>7500000-9499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9500000-9999999</Range>
          <Length>5</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-608</Prefix>
      <Agency>North Macedonia</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0999999</Range>
          <Length>1</Length>
        </Rule>
        <Rule>
          <Range>1000000-1999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2000000-4499999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>4500000-6499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>6500000-6999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>7000000-9999999</Range>
          <Length>1</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-609</Prefix>
      <Agency>Lithuania</Agency>
      <Rules>
        <Rule>
          <Range>0000000-3999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>4000000-7999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>8000000-9499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9500000-9999999</Range>
          <Length>5</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-611</Prefix>
      <Agency>Thailand</Agency>
      <Rules>
        <Rule>
          <Range>0000000-9999999</Range>
          <Length>0</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-612</Prefix>
      <Agency>Peru</Agency>
      <Rules>
        <Rule>
          <Range>0000000-2999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>3000000-3999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>4000000-4499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>4500000-4999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>5000000-5299999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>5300000-9899999</Range>
          <Length>0</Length>
        </Rule>
        <Rule>
          <Range>9900000-9999999</Range>
          <Length>5</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-613</Prefix>
      <Agency>Mauritius</Agency>
      <Rules>
        <Rule>
          <Range>0000000-9999999</Range>
          <Length>1</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-614</Prefix>
      <Agency>Lebanon</Agency>
      <Rules>
        <Rule>
          <Range>0000000-3999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>4000000-7999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>8000000-9499999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>9500000-9999999</Range>
          <Length>5</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-615</Prefix>
      <Agency>Hungary</Agency>
      <Rules>
        <Rule>
          <Range>0000000-0999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>1000000-4999999</Range>
          <Length>3</Length>
        </Rule>
        <Rule>
          <Range>5000000-7999999</Range>
          <Length>4</Length>
        </Rule>
        <Rule>
          <Range>8000000-8999999</Range>
          <Length>5</Length>
        </Rule>
        <Rule>
          <Range>9000000-9999999</Range>
          <Length>0</Length>
        </Rule>
      </Rules>
    </Group>
    <Group>
      <Prefix>978-616</Prefix>
      <Agency>Thailand</Agency>
      <Rules>
        <Rule>
          <Range>0000000-1999999</Range>
          <Length>2</Length>
        </Rule>
        <Rule>
          <Range>2000000-6999999</Range>